// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAOMUXsxWqAl0mw-uBbV8pqaPJC3_1l48',
    appId: '1:332322224014:web:f268f215f58c6dbf8256df',
    messagingSenderId: '332322224014',
    projectId: 'motorcycle-picker',
    authDomain: 'motorcycle-picker.firebaseapp.com',
    storageBucket: 'motorcycle-picker.appspot.com',
    measurementId: 'G-E3QMM41CLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgEoYKKrJm8t57ul-ba0B7MajyRi-VrY',
    appId: '1:332322224014:android:a107c06a660dc2608256df',
    messagingSenderId: '332322224014',
    projectId: 'motorcycle-picker',
    storageBucket: 'motorcycle-picker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3TelZwgyorGNnfqvmnFt0pvP1oriDXkQ',
    appId: '1:332322224014:ios:b702214b40c838488256df',
    messagingSenderId: '332322224014',
    projectId: 'motorcycle-picker',
    storageBucket: 'motorcycle-picker.appspot.com',
    iosClientId: '332322224014-kfbah0ql1aibjas029l33t5j4uvdgi5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorcyclePicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3TelZwgyorGNnfqvmnFt0pvP1oriDXkQ',
    appId: '1:332322224014:ios:b702214b40c838488256df',
    messagingSenderId: '332322224014',
    projectId: 'motorcycle-picker',
    storageBucket: 'motorcycle-picker.appspot.com',
    iosClientId: '332322224014-kfbah0ql1aibjas029l33t5j4uvdgi5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorcyclePicker',
  );
}
